# Generated by Django 4.0.1 on 2022-04-04 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LabStaff', '0004_labreports_patient_diagnosis'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabStaff',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('staff_name', models.CharField(max_length=1000)),
            ],
        ),
    ]
