# Generated by Django 4.0.1 on 2022-04-02 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InsuranceStaff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceClaimRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('patient_firstname', models.CharField(default='fn', max_length=100)),
                ('patient_lastname', models.CharField(default='ln', max_length=100)),
                ('policy_id', models.IntegerField()),
                ('patient_age', models.IntegerField()),
                ('patient_address', models.CharField(max_length=1000)),
                ('patient_phone_no', models.IntegerField()),
                ('patient_email', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InsurancePolicies',
            fields=[
                ('policy_id', models.AutoField(primary_key=True, serialize=False)),
                ('policy_name', models.CharField(max_length=1000)),
                ('coverage_plans', models.CharField(max_length=1000)),
                ('insurance_amt', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='insuranceclaimdetails',
            name='id',
        ),
        migrations.RemoveField(
            model_name='insuranceclaimdetails',
            name='insurance_name',
        ),
        migrations.AddField(
            model_name='insuranceclaimdetails',
            name='claim_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='insuranceclaimdetails',
            name='claim_transaction_status',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='insuranceclaimdetails',
            name='policy_name',
            field=models.CharField(default='pn', max_length=1000),
        ),
    ]
