# Generated by Django 4.0.1 on 2022-04-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InsuranceStaff', '0002_insuranceclaimregister_insurancepolicies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceclaimdetails',
            name='claim_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='insuranceclaimdetails',
            name='policy_name',
            field=models.CharField(max_length=1000),
        ),
    ]
