# Generated by Django 4.0.1 on 2022-04-04 22:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InsuranceStaff', '0005_delete_insurancestaff'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceclaimdetails',
            name='claim_transaction_id',
            field=models.CharField(default='#C', max_length=100),
        ),
        migrations.AlterField(
            model_name='insuranceclaimregister',
            name='patient_age',
            field=models.IntegerField(max_length=3),
        ),
        migrations.AlterField(
            model_name='insuranceclaimregister',
            name='patient_email',
            field=models.EmailField(max_length=254, null=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='insuranceclaimregister',
            name='patient_phone_no',
            field=models.IntegerField(max_length=10),
        ),
    ]
