# Generated by Django 4.0.1 on 2022-04-04 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalStaff', '0003_hospitalstaff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HospitalStaff',
        ),
    ]
