# Generated by Django 4.0.1 on 2022-04-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalStaff', '0005_appointmentdetails_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentdetails',
            name='patient_diagnosis',
            field=models.CharField(default='', max_length=255),
        ),
    ]
