# Generated by Django 4.0.1 on 2022-04-06 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalStaff', '0006_alter_appointmentdetails_patient_diagnosis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentdetails',
            name='transaction_status',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
