# Generated by Django 4.0.1 on 2022-04-05 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminSHS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetails',
            name='employee_username',
            field=models.CharField(default='bcd', max_length=255),
        ),
    ]
