# Generated by Django 4.0.1 on 2022-03-31 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDetails',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_age', models.IntegerField()),
                ('patient_weight', models.CharField(max_length=100)),
                ('patient_height', models.CharField(max_length=100)),
                ('patient_address', models.CharField(max_length=1000)),
                ('patient_phone_no', models.IntegerField()),
                ('patient_email', models.EmailField(max_length=254, null=True)),
                ('doctor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Doctors.doctordetails')),
            ],
        ),
    ]
