# Generated by Django 4.0.1 on 2022-04-05 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdetails',
            name='doctor_id',
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='change_request_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='request_info',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
