# Generated by Django 4.0.1 on 2022-04-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patients', '0002_remove_patientdetails_doctor_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdetails',
            name='card_details',
            field=models.IntegerField(default=0),
        ),
    ]
