# Generated by Django 4.0.1 on 2022-04-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patients', '0003_patientdetails_card_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetails',
            name='card_details',
            field=models.IntegerField(),
        ),
    ]
