# Generated by Django 4.0.1 on 2022-03-31 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorDetails',
            fields=[
                ('doctor_id', models.AutoField(primary_key=True, serialize=False)),
                ('doctor_name', models.CharField(max_length=1000)),
                ('doctor_spec', models.CharField(max_length=1000)),
                ('slot', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='labTests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField(default=0)),
                ('appointment_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=1000)),
                ('last_name', models.CharField(max_length=1000)),
                ('requested_date', models.DateField(blank=True, null=True)),
                ('doctor_id', models.IntegerField(default=0)),
                ('patient_diagnosis', models.CharField(default='adding....', max_length=255)),
                ('lab_test', models.CharField(default='adding....', max_length=255)),
                ('lab_test_status', models.CharField(default='adding....', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='prescriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField(default=0)),
                ('appointment_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=1000)),
                ('last_name', models.CharField(max_length=1000)),
                ('requested_date', models.DateField(blank=True, null=True)),
                ('doctor_id', models.IntegerField(default=0)),
                ('patient_diagnosis', models.CharField(default='adding....', max_length=255)),
                ('drug', models.CharField(default='adding....', max_length=255)),
                ('unit', models.CharField(default='adding....', max_length=255)),
                ('dosage', models.IntegerField(default='adding....', max_length=255)),
                ('prescription_text', models.CharField(default='adding....', max_length=255)),
            ],
        ),
    ]
