# Generated by Django 4.0.1 on 2022-04-02 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptions',
            name='dosage',
            field=models.IntegerField(default='adding....'),
        ),
    ]
