# Generated by Django 4.0.1 on 2022-04-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0002_alter_prescriptions_dosage'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtests',
            name='lab_report',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='labtests',
            name='lab_report_status',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='labtests',
            name='lab_test',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='labtests',
            name='lab_test_status',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='labtests',
            name='patient_diagnosis',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='prescriptions',
            name='dosage',
            field=models.IntegerField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='prescriptions',
            name='drug',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='prescriptions',
            name='patient_diagnosis',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='prescriptions',
            name='prescription_text',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='prescriptions',
            name='unit',
            field=models.CharField(default='', max_length=255),
        ),
    ]
