# Generated by Django 4.0.1 on 2022-04-06 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0004_doctordetails_doctor_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctordetails',
            name='doctor_username',
            field=models.CharField(max_length=100),
        ),
    ]
